# render.yaml
# Infrastructure blueprint for deployment on Render.com

# ----------------------------------------------------------------
# All Services (API, Workers, Redis) must be under the 'services:' key.
# ----------------------------------------------------------------
services:
  # 1. The main Flask API (Web Service)
  - type: web
    name: microcap-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    region: oregon
    plan: standard
    healthCheckPath: /api/v1/health
    envVars:
      - fromGroup: microcap-secrets
      # Link Database and Redis automatically
      - key: DATABASE_URL
        fromDatabase:
          name: microcap-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: microcap-redis
          property: connectionString

  # 2. Background Worker (Celery)
  - type: worker
    name: microcap-worker
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    region: oregon
    plan: standard
    # Command to start the Celery worker (Assumes Celery app is in backend/tasks.py)
    startCommand: "celery -A tasks:celery_app worker --loglevel=INFO"
    envVars:
      - fromGroup: microcap-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: microcap-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: microcap-redis
          property: connectionString

  # 3. Celery Beat Scheduler
  - type: worker
    name: microcap-scheduler
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    region: oregon
    plan: starter
    startCommand: "celery -A tasks:celery_app beat --loglevel=INFO"
    envVars:
      - fromGroup: microcap-secrets
      - key: REDIS_URL
        fromService:
          type: redis
          name: microcap-redis
          property: connectionString

  # 4. Redis (Task Queue Broker) - Must be defined as a service
  - type: redis
    name: microcap-redis
    region: oregon
    plan: starter
    # maxmemoryPolicy defines how Redis behaves when memory is full. 'noeviction' is standard for brokers.
    maxmemoryPolicy: noeviction
    # ipAllowList is required for Redis services; Render manages this automatically for internal connections.
    ipAllowList: [] 

# ----------------------------------------------------------------
# PostgreSQL Databases are defined under the 'databases:' key.
# ----------------------------------------------------------------
databases:
  # 5. Production Database (PostgreSQL)
  - name: microcap-db
    region: oregon
    plan: standard

# ----------------------------------------------------------------
# Shared Secrets Group (Configure values securely in the Render Dashboard)
# ----------------------------------------------------------------
envVarGroups:
  - name: microcap-secrets
    envVars:
      - key: POLYGON_API_KEY
        sync: false
      - key: TIINGO_API_KEY
        sync: false
      - key: SSRV_WEBHOOK_SECRET
        sync: false
      # Add Firebase credentials/secrets here
