# ios/fastlane/Snapfile

# Devices required by App Store Connect standards
devices([
  "iPhone 15 Pro Max", # 6.7 inch display
  "iPhone 8 Plus",     # 5.5 inch display
  "iPad Pro (12.9-inch) (6th generation)"
])

languages(["en-US"])
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
